### ISSUE TITLE
[Bug]: Can't use `DebugDraw` in a `Viewport`-extending scripts

### ISSUE THREAD

**Issue by mieldepoche** [DmitriySalnikov/godot_debug_draw_3d#15]
### Godot version

4.0.3

### DebugDraw3D version

1.0.0 (downloaded from the asset lib, not sure where to check for the version)

### On which operating systems the error occurs

Linux

### Using which renderers the error occurs

Vulkan, GLES3

### Issue description

For some reason when trying to use `DebugDraw` in a `Viewport` script (or `SubViewport`, etc.) it refuses to work, yielding two possible errors:

- "Cannot find member "draw_a" in base "Viewport.DebugDraw"."  -- when typing, and
- "The native enum "DebugDraw" does not behave like Dictionary and does not have methods of its own." when typed a valid member/function name.

Those errors don't show up on a `Node`-extending script, and the DebugDraw thing seem to work correctly in a `Node` script.

[simplescreenrecorder-2023-05-30_15.22.29.webm](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/71937306/14f8353f-2ad4-4191-8ca3-7e426f233de0)

### Steps to reproduce

create a script file in a project with DebugDraw installed, and put that in it:
```gdscript
extends Viewport

func _process(delta: float) -> void:
    DebugDraw.draw_sphere(Vector3.ZERO)
```

### Minimal reproduction project

(contains literally a clean install of the addon from the asset lib and the above script)
[DebugDrawViewportBug.zip](https://github.com/DmitriySalnikov/godot_debug_draw_3d/files/11600511/DebugDrawViewportBug.zip)

**Comment by DmitriySalnikov** [comment]
This is because the viewports have the `debug_draw` parameter and the associated enum with it. I didn't think much about it before, but I added an abbreviation for `DebugDraw` to `Dbg3` in advance. You can use it to avoid conflict.

In this case, it's probably worth completely renaming the singleton to something like `DebugDraw3` and adding `DebugDraw2` (for 2d).
Or maybe `Dd3d` or `Dd3` is better? What do you think is the best name to use?

**Comment by mieldepoche** [comment]
Oooh okay I see, thanks!
As for the name I would vote for `DebugDraw3D/2D` as I'm personally okay with "long" explicit names like this.
