### ISSUE TITLE
[Feature Request]: Viewport Scaling Visibility

### ISSUE THREAD

**Issue by blast-harbour** [DmitriySalnikov/godot_debug_draw_3d#26]
### Feature description

My project uses a 4k base resolution to make use of high resolution UI assets. as a result, the lines drawn by debug draw 3d become too thin to see often.
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/60982612/6d7cee09-8920-405b-9a05-aebc953f7998)

### Implementation Ideas

Maybe a way to set line thickness would be helpful?

**Comment by DmitriySalnikov** [comment]
I think this relates to #3

**Comment by kitbdev** [comment]
Using anti-aliasing on the lines should fix this and would allow for the lines to stay the same size. [For reference I'm thinking of this](https://acegikmo.com/shapes/docs/#anti-aliasing)

**Comment by DmitriySalnikov** [comment]
In this addon, I just draw wireframes that the engine displays with a thickness of 1 pixel at any resolutions. So I'm not sure if anti-aliasing will help.

---

It looks a little better with anti-aliasing, but I can't check it in 4K or even 1440p.

No AA:
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/00b462c8-e7a8-40b0-9e0c-e18ac6e3b922)

MSAA 8x:
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/0ce1ec87-9e0c-413c-8af4-fd17510736e3)

TAA:
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/15beed0b-98b6-444e-a78c-56d5a5568ce8)

**Comment by kitbdev** [comment]
Possibly related: https://github.com/godotengine/godot/issues/37016
Is this in Vulkan or the Compatibility OpenGL renderer?
I'm also curious what the 3D scene view looks like at 4k, does the grid there have the same issues?

**Comment by DmitriySalnikov** [comment]
Does this version look better (in terms of visibility)? [Link to my personal server with a temporary domain name](https://site.dmitriysalnikov.tw1.ru/web_apps/dd3d/index.html)
In this demo, all meshes are replaced with volumetric ones with a thickness of `0.1`. 

Unlike the usual wireframe lines, which are always rendered as 1px, these meshes change their size depending on the distance.
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/c7ff4fec-e559-4bd4-bfb8-730ceab6f00d)

There are still distortion issues right now (with certain transformations), and I don't know if I can fix it.
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/98abe7ce-9691-4688-be46-78879b50dcb8)

And I have not decided how to change the API so that it is possible to switch to regular or volumetric models. Add another parameter to all `draw_*` methods? Or call another method before `draw_*`, for example `set_line_thickness`?

**Comment by DmitriySalnikov** [comment]
https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/f25194cb-933d-4792-9d21-d7036b8ffe7c

**Comment by DmitriySalnikov** [comment]
Fixed in f96700bcb4ea44ae45dae4ea81246aaf462c6d76
