### ISSUE TITLE
[Feature Request]: iOS Support

### ISSUE THREAD

**Issue by jbromberg** [DmitriySalnikov/godot_debug_draw_3d#27]
### Feature description

We're developing games for iOS and are unfortunately unable to use this plugin on device. Adding support for iOS would be great.

**Comment by DmitriySalnikov** [comment]
Most likely it is already supported. The only problem is that I don't have any Apple devices and my PC isn't modern enough to support macOS emulation (especially with iOS emulation inside it), at least at 30 stable fps (or even 10 fps..).
Because of this, I can't test the build for iOS, confirm that it works and publish the changes.

So you can donate to me for a new PC or you can just build the addon for iOS yourself from source. Or you can even update the build script and do a PR.

**Comment by jbromberg** [comment]
> Most likely it is already supported. The only problem is that I don't have any Apple devices and my PC isn't modern enough to support macOS emulation (especially with iOS emulation inside it), at least at 30 stable fps (or even 10 fps..). Because of this, I can't test the build for iOS, confirm that it works and publish the changes.
> 
> So you can donate to me for a new PC or you can just build the addon for iOS yourself from source. Or you can even update the build script and do a PR.

how much of a donation do you need?

**Comment by DmitriySalnikov** [comment]
Since I have a very old processor, I will have to change the motherboard, RAM, processor and cooler. ~$400-500 for a good build. And then a whole day to figure out how to run macOS 😅

In fact, right now I can look at someone's build scripts and integrate them into my scripts, but I still won't be able to test the library.

**Comment by DmitriySalnikov** [comment]
Fixed in #36
