### ISSUE TITLE
[Bug]: Doesn't render 3D debugdraws in subviewports without a main viewport camera

### ISSUE THREAD

**Issue by N-e-m** [DmitriySalnikov/godot_debug_draw_3d#47]
### Godot version

4.2.2.stable

### DebugDraw3D version

4.1.3+

### On which operating systems the error occurs

Windows

### Issue description

It seems like your frustum culling relies on an active camera in the main viewport of a scene. I'd like to be able to assign a different camera for instances when I'm using subviewports. Or even better, automatically detect the relevant camera based on the node calling the draw functions parent viewport.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by DmitriySalnikov** [comment]
> ### DebugDraw3D version
> 4.1.3+

This is not the DD3D version, this is the minimum version of Godot that it supports.

> It seems like your frustum culling relies on an active camera in the main viewport of a scene. I'd like to be able to assign a different camera for instances when I'm using subviewports. 

In fact, frustum culling depends on the current viewport in scoped_config.

Try to change the current/scoped viewport of DD3D https://dd3d.dmitriysalnikov.ru/docs/1.4.2/classDebugDraw3DScopeConfig.html#aa5cc8163e120284dc83f2b8e46534277
`DebugDraw3DScopeConfig` has a usage example in the description.


> Or even better, automatically detect the relevant camera based on the node calling the draw functions parent viewport.

Is it possible to get a calling node in godot?


<sub>I apologize for the long answer. I read the message almost immediately, but then I forgot about it :(</sub>

**Comment by DmitriySalnikov** [comment]
@N-e-m Did the message above help you?

**Comment by lmorao** [comment]
I've tried doing this and it worked for me.
For reference I have this setup

<img width="386" alt="image" src="https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/57681540/c898ef5c-973a-4213-b659-799f176b11d7">

And then on a def _physics_process(delta) I have this code
```
	var _s = DebugDraw3D.new_scoped_config().set_viewport(Globals.v.main_viewport.viewport)
	for point in points:	
		DebugDraw3D.draw_sphere(point, 2.5)
```
Before doing this, it was not drawing.
Also, as per the documentation, you need to use the ```var _s =```, otherwise it won't work.

**Comment by jasonswearingen** [comment]
I have this problem because I use the editor's cinematic camera.  this is not the actual viewport as obtained if you were to get the editor camera 0's viewport.   I worked around this by, when running in the editor, I manually overwrite the editor camera's transforms to match my current camera.   it's a hack but it make DD3D stuff show up properly.
