### ISSUE TITLE
[Feature Request]: Enable debug drawing in Release (published) builds

### ISSUE THREAD

**Issue by Eudaimonium** [DmitriySalnikov/godot_debug_draw_3d#51]
### Feature description

I see that the runtime debug draws are disabled via following snippet in the SConstruct file: 

```
if "release" in env["target"] and not env["force_enabled_dd3d"]:
        env.Append(CPPDEFINES=["DISABLE_DEBUG_RENDERING"])
```

If I'm correct this means that I need to rebuild the plugin from source if I wish to enable runtime debug draws. 

What would be the easiest way for me to do this, or alternatively, could you provide an opt-in for this?

**Comment by DmitriySalnikov** [comment]
> What would be the easiest way for me to do this

I think the easiest way is to read the documentation
https://dd3d.dmitriysalnikov.ru/docs/1.4.4/md_docs_2Export.html
So for almost all platforms, debug rendering is activated in the release version by adding a one flag.

But if you need it for Android, then you will have to build it manually, because the libraries for Android are large.

**Comment by Eudaimonium** [comment]
Ah I have missed this part of the documentation, thank you!
